### ISSUE TITLE
There are a lot of errors after upgraded to 0.50.2

### ISSUE THREAD

**Issue by madeinquant** [fsprojects/Fabulous#596]
There are  a lot of errors after upgraded to 0.50.2, no errors were found when compiled with 0.42.

```
rowdefs = [ for i in 1..33 -> "0.5*" ],
coldefs = [ for i in 1..19 -> "0.5*" ], rowSpacing = 0., columnSpacing = 0.,
```
1. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(48,48): Error FS0001: This expression was expected to have type    'Dimension'    but here has type    'string' (FS0001) (SqueakyApp)
2. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(48,48): Error FS0001: This expression was expected to have type    'Dimension'    but here has type    'string' (FS0001) (SqueakyApp)
```
.GridRow(0).GridColumn(0).GridRowSpan(33).GridColumnSpan(19)
```
3. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(36,36): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
4. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(104,104): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
5. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(36,36): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
6. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(90,90): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
7. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(85,85): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
8. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(85,85): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
9. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(85,85): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
10. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(88,88): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)
11. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(97,97): Error FS0001: This expression was expected to have type    'Thickness'    but here has type    'float' (FS0001) (SqueakyApp)
```
 (children = [ View.BoxView(heightRequest = 5.,
```
12. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(75,75): Error FS0495: The member or object constructor 'BoxView' has no argument or settable return property 'heightRequest'. The required signature is static member View.BoxView : ?color:Color * ?anchorX:float * ?anchorY:float * ?automationId:string * ?backgroundColor:Color * ?behaviors:ViewElement list * ?classId:string * ?cornerRadius:CornerRadius * ?created:(BoxView -> unit) * ?effects:ViewElement list * ?flowDirection:FlowDirection * ?focused:(FocusEventArgs -> unit) * ?gestureRecognizers:ViewElement list * ?height:float * ?horizontalOptions:LayoutOptions * ?inputTransparent:bool * ?isEnabled:bool * ?isTabStop:bool * ?isVisible:bool * ?margin:Thickness * ?menu:ViewElement * ?minimumHeight:float * ?minimumWidth:float * ?opacity:float * ?ref:ViewRef<BoxView> * ?resources:(string * obj) list * ?rotation:float * ?rotationX:float * ?rotationY:float * ?scale:float * ?scaleX:float * ?scaleY:float * ?shellBackButtonBehavior:ViewElement * ?shellBackgroundColor:Color * ?shellDisabledColor:Color * ?shellFlyoutBehavior:FlyoutBehavior * ?shellForegroundColor:Color * ?shellNavBarIsVisible:bool * ?shellSearchHandler:ViewElement * ?shellTabBarBackgroundColor:Color * ?shellTabBarDisabledColor:Color * ?shellTabBarForegroundColor:Color * ?shellTabBarIsVisible:bool * ?shellTabBarTitleColor:Color * ?shellTabBarUnselectedColor:Color * ?shellTitleColor:Color * ?shellTitleView:ViewElement * ?shellUnselectedColor:Color * ?style:Style * ?styleClasses:string list * ?styleId:string * ?styleSheets:StyleSheets.StyleSheet list * ?styles:Style list * ?tabIndex:int * ?tag:obj * ?translationX:float * ?translationY:float * ?unfocused:(FocusEventArgs -> unit) * ?verticalOptions:LayoutOptions * ?visual:IVisual * ?width:float -> ViewElement. (FS0495) (SqueakyApp)
13. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(75,75): Error FS0495: The member or object constructor 'ListView' has no argument or settable return property 'heightRequest'. The required signature is static member View.ListView : ?items:ViewElement list * ?anchorX:float * ?anchorY:float * ?automationId:string * ?backgroundColor:Color * ?behaviors:ViewElement list * ?classId:string * ?created:(CustomListView -> unit) * ?effects:ViewElement list * ?flowDirection:FlowDirection * ?focused:(FocusEventArgs -> unit) * ?footer:ViewElement * ?gestureRecognizers:ViewElement list * ?hasUnevenRows:bool * ?header:ViewElement * ?height:float * ?horizontalOptions:LayoutOptions * ?horizontalScrollBarVisibility:ScrollBarVisibility * ?inputTransparent:bool * ?isEnabled:bool * ?isGroupingEnabled:bool * ?isPullToRefreshEnabled:bool * ?isRefreshing:bool * ?isTabStop:bool * ?isVisible:bool * ?itemAppearing:(int -> unit) * ?itemDisappearing:(int -> unit) * ?itemSelected:(int option -> unit) * ?itemTapped:(int -> unit) * ?margin:Thickness * ?menu:ViewElement * ?minimumHeight:float * ?minimumWidth:float * ?opacity:float * ?ref:ViewRef<CustomListView> * ?refreshCommand:(unit -> unit) * ?refreshCommandCanExecute:bool * ?refreshControlColor:Color * ?refreshing:(unit -> unit) * ?resources:(string * obj) list * ?rotation:float * ?rotationX:float * ?rotationY:float * ?rowHeight:int * ?scale:float * ?scaleX:float * ?scaleY:float * ?scrolled:(ScrolledEventArgs -> unit) * ?selectedItem:int option * ?selectionMode:ListViewSelectionMode * ?separatorColor:Color * ?separatorVisibility:SeparatorVisibility * ?shellBackButtonBehavior:ViewElement * ?shellBackgroundColor:Color * ?shellDisabledColor:Color * ?shellFlyoutBehavior:FlyoutBehavior * ?shellForegroundColor:Color * ?shellNavBarIsVisible:bool * ?shellSearchHandler:ViewElement * ?shellTabBarBackgroundColor:Color * ?shellTabBarDisabledColor:Color * ?shellTabBarForegroundColor:Color * ?shellTabBarIsVisible:bool * ?shellTabBarTitleColor:Color * ?shellTabBarUnselectedColor:Color * ?shellTitleColor:Color * ?shellTitleView:ViewElement * ?shellUnselectedColor:Color * ?style:Style * ?styleClasses:string list * ?styleId:string * ?styleSheets:StyleSheets.StyleSheet list * ?styles:Style list * ?tabIndex:int * ?tag:obj * ?translationX:float * ?translationY:float * ?unfocused:(FocusEventArgs -> unit) * ?verticalOptions:LayoutOptions * ?verticalScrollBarVisibility:ScrollBarVisibility * ?visual:IVisual * ?width:float -> ViewElement. (FS0495) (SqueakyApp)
14. /eUSB/sync/csharp/Xamarin/SqueakyApp/SqueakyApp/SqueakyApp.fs(36,36): Error FS0039: The field, constructor or member 'GridRow' is not defined. (FS0039) (SqueakyApp)

**Comment by TimLariviere** [comment]
@madeinquant v0.50 introduced a lot of breaking changes. You can find a migration guide here to learn what changed: https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/migration-guide-to-0.50.html (GridRow/GridColumn can be simplified to Row/Column)

You seem to have created the SqueakyApp sample, so I would recommend you to run the following commands:
```
dotnet new -u Fabulous.XamarinForms.Templates
dotnet new -i Fabulous.XamarinForms.Templates
dotnet new fabulous-xf-app -n SqueakyApp
```

This will recreate the SqueakyApp with a code compatible with 0.50

**Comment by madeinquant** [comment]
@TimLariviere Thank you
